In [1]:
# 1 - convert list into one dimensional numpy array.
import numpy as np
original_list = [12.23, 13.32, 100, 36.32]
arr = np.array(original_list)
print(arr)
print(type(original_list))
print(type(arr))


[ 12.23  13.32 100.    36.32]
<class 'list'>
<class 'numpy.ndarray'>


In [21]:
# 2 - Create a 3x3 matrix with values ranging from 2 to 10.
matrix = np.matrix([[2,3,4],[4,5,6],[7,8,9]])
print(matrix)
# Another method
matrix1 = np.arange(2,11).reshape(3,3)
matrix1

[[2 3 4]
 [4 5 6]
 [7 8 9]]


array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [ ]:
# 3 - Array size of 10 and update the 6 value to 11.
arr = np.zeros(10)
arr[5] = 11
arr

array([ 0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.,  0.])

In [ ]:
# 4 - Reverse an array.
arr = np.arange(12,39)
print(arr)
rev_arr = arr[::-1]
print(rev_arr)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]
[38 37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15
 14 13 12]


In [47]:
# 5 - create a 2d array with 1 on the border and 0 inside.
arr = np.ones((5,5))
print(arr)
arr[1:-1,1:-1] = 0
arr

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [53]:
# 6 - Border filled with zero's.
arr = np.ones((3,3))
print(arr)
border_arr = np.pad(arr,pad_width=1,mode='constant',constant_values=0)
print(border_arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [4]:
# 7 - CheckBoard pattern
check_board = np.zeros((8,8),dtype = int)
print(check_board)
check_board[1::2, ::2] = 1
check_board[::2, 1::2] = 1
print(check_board)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [59]:
# 8 - list and tuple into an array
li = [1,2,3,4,5,6,7,8]
arr = np.array(li)
print(arr)
tp = (1,2,3)
arr_1 = np.array(tp)
print(arr_1)

[1 2 3 4 5 6 7 8]
[1 2 3]


In [60]:
# 9 - Append values to the end of an array.
arr = np.array([10,20,30])
print(arr)
values = [40,50,60,70,80,90]
new_arr = np.append(arr,values)
new_arr

[10 20 30]


array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [61]:
# 10 - real and imaginary parts of an array.
arr = np.array([1+0j, 0.70710678+0.70710678j])
print(arr)
real_part = arr.real
imag_part = arr.imag
print(real_part)
print(imag_part)

[1.        +0.j         0.70710678+0.70710678j]
[1.         0.70710678]
[0.         0.70710678]
