In [1]:
# 1 - convert list into one dimensional numpy array.
import numpy as np
original_list = [12.23, 13.32, 100, 36.32]
arr = np.array(original_list)
print(arr)
print(type(original_list))
print(type(arr))


[ 12.23  13.32 100.    36.32]
<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
# 2 - Create a 3x3 matrix with values ranging from 2 to 10.
matrix = np.matrix([[2,3,4],[4,5,6],[7,8,9]])
print(matrix)
# Another method
# shape - change the shape of array and it will change 1d array into 3*3 array
matrix1 = np.arange(2,11).reshape(3,3)
matrix1

[[2 3 4]
 [4 5 6]
 [7 8 9]]


array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [ ]:
# 3 - Array size of 10 and update the 6 value to 11.
arr = np.zeros(10)
arr[5] = 11
arr

array([ 0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.,  0.])

In [ ]:
# 4 - Reverse an array.
arr = np.arange(12,39)
print(arr)
rev_arr = arr[::-1]
print(rev_arr)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]
[38 37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15
 14 13 12]


In [47]:
# 5 - create a 2d array with 1 on the border and 0 inside.
arr = np.ones((5,5))
print(arr)
arr[1:-1,1:-1] = 0
arr

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [53]:
# 6 - Border filled with zero's.
arr = np.ones((3,3))
print(arr)
border_arr = np.pad(arr,pad_width=1,mode='constant',constant_values=0)
print(border_arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [4]:
# 7 - CheckBoard pattern
check_board = np.zeros((8,8),dtype = int)
print(check_board)
check_board[1::2, ::2] = 1
check_board[::2, 1::2] = 1
print(check_board)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [59]:
# 8 - list and tuple into an array
li = [1,2,3,4,5,6,7,8]
arr = np.array(li)
print(arr)
tp = (1,2,3)
arr_1 = np.array(tp)
print(arr_1)

[1 2 3 4 5 6 7 8]
[1 2 3]


In [60]:
# 9 - Append values to the end of an array.
arr = np.array([10,20,30])
print(arr)
values = [40,50,60,70,80,90]
new_arr = np.append(arr,values)
new_arr

[10 20 30]


array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [61]:
# 10 - real and imaginary parts of an array.
arr = np.array([1+0j, 0.70710678+0.70710678j])
print(arr)
real_part = arr.real
imag_part = arr.imag
print(real_part)
print(imag_part)

[1.        +0.j         0.70710678+0.70710678j]
[1.         0.70710678]
[0.         0.70710678]


In [14]:
# 11 - Number of elements in array
arr = np.array(([10,20,30]))
# size method give length of an array
arr_size = arr.size
# itemsize method gives size of one element in bytes
arr_byte = arr.itemsize
# nbytes gives total bytes consumed by array
total_arr = arr.nbytes
print("Size of the array :",arr_size)
print("Length of one array element in bytes:", arr_byte)
print("Total bytes consumed by the elements of the array:", total_arr)


Size of the array : 3
Length of one array element in bytes: 8
Total bytes consumed by the elements of the array: 24


In [ ]:
# 12 - Common values between two arrays
arr1 = np.array([0,10,20,40,60])
arr2 = np.array([10,30,40])
# intersect1d method return common elements between two arrays
common_arr_elements = np.intersect1d(arr1,arr2)
print(common_arr_elements)

[10 40]


In [ ]:
# 13 - set difference of two arrays
arr_1 = np.array([0,10,20,40,60,80])
arr_2 = np.array([10,30,40,50,70,90])
# setdiff1d method it will find differnece (arr_1 - arr_2)
diff_arr = np.setdiff1d(arr_1,arr_2)
print(diff_arr)

[30 50 70 90]


In [ ]:
# 14 - set exclusive of two arrays
arr_1 = np.array([0,10,20,40,60,80])
arr_2 = np.array([10,30,40,50,70])
# set exclusive-or checks Unique values that are in only one (not both) of the input arrays
result = np.setxor1d(arr_1,arr_2)
print(result)

[ 0 20 30 50 60 70 80]


In [ ]:
# 15 - compare two arrays using numpy
a = np.array([1,2])
b = np.array([4,5])
# [False False] - each comparision is done element by element
print(a > b)
print(a >= b)
print(a < b)
print(a <= b)

[False False]
[False False]
[ True  True]
[ True  True]


In [25]:
# 15 - Program to save a NumPy array to a text file.
arr = np.array([10,20,30,40,50])
# savetxt - save array to text file
np.savetxt('array_data.txt',arr,fmt="%d")
print("Numpy array saved into text file")
# loadtxt - load from the file
data = np.loadtxt('array_data.txt',dtype=int)
print(data)

Numpy array saved into text file
[10 20 30 40 50]


In [ ]:
# 16 - contiguous flatten array
arr = np.array([[10,20,30],
                [20,40,50]])
print(arr)
# flatten() - creates contiguous flatten array
flat_arr = arr.flatten()
print(flat_arr)

[[10 20 30]
 [20 40 50]]
[10 20 30 20 40 50]


In [ ]:
# 17 - Change the data type of an array
arr = np.array([[2,4,6],
                [6,8,10]],dtype=np.int32)
# dtype - checks array data type
# astype - change data type
new_arr = arr.astype(np.float32)
print(new_arr)

[[ 2.  4.  6.]
 [ 6.  8. 10.]]


In [ ]:
# 18 - Diagonal matrix
# built-in method (np.eye)
arr = np.eye(3)
print(arr)
# Another method
ar = np.zeros((3,3))
# fill_diagonal elements becomes one 
np.fill_diagonal(ar,1)
print(ar)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [37]:
# 20 - Concatenate two 2-dimensional arrays.
arr_1 = np.array([[0,1,3],[5,7,9]])
arr_2 = np.array([[0,2,4],[6,8,10]])
# axis = joins arrays column wise
# Columns of arr2 are added to the right of arr1
result = np.concatenate((arr_1,arr_2),axis=1)
print(result)


[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


In [39]:
# 21 - Array immutable
arr = np.array([10,20,30,40,50])
# arr.flags.writeable = False -- makes the array read-only
arr.flags.writeable = False
print("Test the array is read-only or not:")
print("Try to change the value of the first element:")
arr[0] = 1

Test the array is read-only or not:
Try to change the value of the first element:


ValueError: assignment destination is read-only

In [ ]:
# 22 - 